#ifndef _CC1101_DEF_H
#define _CC1101_DEF_H

// config registers
#define CC_IOCFG2           0x00
#define CC_IOCFG1           0x01
#define CC_IOCFG0           0x02
#define CC_FIFOTHR          0x03
#define CC_SYNC1            0x04
#define CC_SYNC0            0x05
#define CC_PKTLEN           0x06
#define CC_PKTCTRL1         0x07
#define CC_PKTCTRL0         0x08
#define CC_ADDR             0x09
#define CC_CHANNR           0x0a
#define CC_FSCTRL1          0x0b
#define CC_FSCTRL0          0x0c
#define CC_FREQ2            0x0d
#define CC_FREQ1            0x0e
#define CC_FREQ0            0x0f
#define CC_MDMCFG4          0x10
#define CC_MDMCFG3          0x11
#define CC_MDMCFG2          0x12
#define CC_MDMCFG1          0x13
#define CC_MDMCFG0          0x14
#define CC_DEVIATN          0x15
#define CC_MCSM2            0x16
#define CC_MCSM1            0x17
#define CC_MCSM0            0x18
#define CC_FOCCFG           0x19
#define CC_BSCFG            0x1a
#define CC_AGCCTRL2         0x1b
#define CC_AGCCTRL1         0x1c
#define CC_AGCCTRL0         0x1d
#define CC_WOREVT1          0x1e
#define CC_WOREVT0          0x1f
#define CC_WORCTRL          0x20
#define CC_FREND1           0x21
#define CC_FREND0           0x22
#define CC_FSCAL3           0x23
#define CC_FSCAL2           0x24
#define CC_FSCAL1           0x25
#define CC_FSCAL0           0x26
#define CC_RCCTRL1          0x27
#define CC_RCCTRL0          0x28
#define CC_FSTEST           0x29
#define CC_PTEST            0x2a
#define CC_AGCTEST          0x2b
#define CC_TEST2            0x2c
#define CC_TEST1            0x2d
#define CC_TEST0            0x2e
// status registers
#define CC_PARTNUM          0x30
#define CC_VERSION          0x31
#define CC_FREQEST          0x32
#define CC_LQI              0x33
#define CC_RSSI             0x34
#define CC_MARCSTATE        0x35
#define CC_WORTIME1         0x36
#define CC_WORTIME0         0x37
#define CC_PKTSTATUS        0x38
#define CC_VCO_VC_DAC       0x39
#define CC_TXBYTES          0x3a
#define CC_RXBYTES          0x3b
#define CC_RCCTRL1_STATUS   0x3c
#define CC_RCCTRL0_STATUS   0x3d
// PA table and fifo
#define CC_PATABLE          0x3e
#define CC_TXFIFO           0x3f
#define CC_RXFIFO           0x3f
// commands
#define CC_SRES             0x30
#define CC_SFSTXON          0x31
#define CC_SXOFF            0x32
#define CC_SCAL             0x33
#define CC_SRX              0x34
#define CC_STX              0x35
#define CC_SIDLE            0x36
#define CC_SWOR             0x38
#define CC_SPWD             0x39
#define CC_SFRX             0x3a
#define CC_SFTX             0x3b
#define CC_SWORRST          0x3c
#define CC_SNOP             0x3d
// SPI header
#define CC_WRITE            0x00
#define CC_WRITE_BURST      0x40
#define CC_READ             0x80
#define CC_READ_BURST       0xc0
// status
#define CC_STATE_MASK        0xf0
#define CC_STATE_IDLE        0x00
#define CC_STATE_RX          0x10
#define CC_STATE_TX          0x20
#define CC_STATE_FSTXON      0x30
#define CC_STATE_CALIBRATE   0x40
#define CC_STATE_SETTLING    0x50
#define CC_STATE_RXOVF       0x60
#define CC_STATE TXOVF       0x70

#endif
